steps:
# Docker Build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'asia-southeast2-docker.pkg.dev/unu-poc/$_IMAGE_NAME/$_IMAGE_NAME:latest', '-t', 'asia-southeast2-docker.pkg.dev/unu-poc/$_IMAGE_NAME/$_IMAGE_NAME:latest', '.']
# Docker Push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-southeast2-docker.pkg.dev/unu-poc/$_IMAGE_NAME/$_IMAGE_NAME:latest']
# Deploy to CloudRun
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['run', 'deploy', '$_IMAGE_NAME', '--image', 'asia-southeast2-docker.pkg.dev/unu-poc/$_IMAGE_NAME/$_IMAGE_NAME:latest', '--region', 'asia-southeast2', '--network', '$_NETWORK_NAME', '--subnet', '$_SUBNET_NAME', '--vpc-egress', 'all-traffic']
options:
  logging: CLOUD_LOGGING_ONLY
  # machineType: E2_HIGHCPU_8